In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.linear_model import LogisticRegression

In [3]:
#csv file from train
df = pd.read_csv('e14_e15_merged_int.csv', sep = ',')


In [4]:
#csv file from test
df_test = pd.read_csv('e16_int.csv', sep = ',')

In [5]:
df.gender.replace(['Male', 'Female'], [1, 0], inplace=True)
df_test.gender.replace(['Male', 'Female'], [1, 0], inplace=True)

In [6]:
X = df.drop("final_grades",1)   #Feature Matrix
y = df["final_grades"]          #Target Variable


In [7]:
X_T = df.drop("final_grades",1)   #Feature Matrix
y_T = df["final_grades"]          #Target Variable

In [8]:
clf = LogisticRegression()
clf.fit(X,y)
y_pred = clf.predict(X_T)

In [9]:
from sklearn.metrics import confusion_matrix
confusion_matrix=confusion_matrix(y_T,y_pred)
print('\nconfusion_matrix | LogisticRegression\n')
print(confusion_matrix)
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.metrics import classification_report

print('\nclassification_report | LogisticRegression\n')
print(classification_report(y_T, y_pred))
print("Accuracy | LogisticRegression:",metrics.accuracy_score(y_T, y_pred),"\n")



confusion_matrix | LogisticRegression

[[272 145   0   0]
 [144 228   0   0]
 [  5  24   0   0]
 [  0   2   0   0]]

classification_report | LogisticRegression

             precision    recall  f1-score   support

          A       0.65      0.65      0.65       417
          B       0.57      0.61      0.59       372
          C       0.00      0.00      0.00        29
          E       0.00      0.00      0.00         2

avg / total       0.59      0.61      0.60       820

Accuracy | LogisticRegression: 0.6097560975609756 



C:\Users\Hassana\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [10]:
from sklearn.naive_bayes import GaussianNB
# Naive Bayes 
classifier = GaussianNB()
classifier.fit(X, y)
y_pred = classifier.predict(X_T)
print('\nconfusion_matrix | Naivebayes\n')
print(confusion_matrix)
print('\nclassification_report | Naive Bayes\n')
print(classification_report(y_T, y_pred))
print("Accuracy | Naive Bayes:",metrics.accuracy_score(y_T, y_pred),"\n") # Model Accuracy: how often is the classifier correct?



confusion_matrix | Naivebayes

[[272 145   0   0]
 [144 228   0   0]
 [  5  24   0   0]
 [  0   2   0   0]]

classification_report | Naive Bayes

             precision    recall  f1-score   support

          A       0.72      0.33      0.45       417
          B       0.47      0.54      0.50       372
          C       0.09      0.59      0.15        29
          E       0.20      1.00      0.33         2

avg / total       0.58      0.44      0.46       820

Accuracy | Naive Bayes: 0.4353658536585366 



In [12]:
from sklearn import svm #Import svm model
clf = svm.SVC(kernel='linear') #Create a svm Classifier
clf.fit(X, y) #Train the model using the training sets

y_pred = clf.predict(X_T)
print('\nconfusion_matrix | SVM\n')
print(confusion_matrix)

print('\nclassification_report | svm\n')
print(classification_report(y_T, y_pred))
print("Accuracy | SVM:",metrics.accuracy_score(y_T, y_pred),"\n") # Model Accuracy



confusion_matrix | SVM

[[272 145   0   0]
 [144 228   0   0]
 [  5  24   0   0]
 [  0   2   0   0]]

classification_report | svm

             precision    recall  f1-score   support

          A       0.66      0.59      0.62       417
          B       0.56      0.67      0.61       372
          C       0.00      0.00      0.00        29
          E       0.00      0.00      0.00         2

avg / total       0.59      0.60      0.59       820

Accuracy | SVM: 0.6036585365853658 



C:\Users\Hassana\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [13]:
from sklearn.neural_network import MLPClassifier
mlp=MLPClassifier()
mlp.fit(X,y)
y_pred=mlp.predict(X_T)
print('\nconfusion_matrix | Multilayer Perceptron\n')
print(confusion_matrix)

print('\nclassification_report | mlp\n')
print(classification_report(y_T, y_pred))
print("Accuracy | MLP:",metrics.accuracy_score(y_T, y_pred),"\n")


confusion_matrix | Multilayer Perceptron

[[272 145   0   0]
 [144 228   0   0]
 [  5  24   0   0]
 [  0   2   0   0]]

classification_report | mlp

             precision    recall  f1-score   support

          A       0.58      0.85      0.69       417
          B       0.61      0.35      0.44       372
          C       0.00      0.00      0.00        29
          E       0.00      0.00      0.00         2

avg / total       0.57      0.59      0.55       820

Accuracy | MLP: 0.5902439024390244 



C:\Users\Hassana\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
