In [22]:
import numpy as np
import pandas as pd

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:

#csv file from train
df = pd.read_csv('e14_e15_e16_merged.csv', sep = ',')


In [25]:
df.gender.replace(['Male', 'Female'], [1, 0], inplace=True)


In [26]:
X = df.drop("final_grades",1)   #Feature Matrix
y = df["final_grades"]          #Target Variable


In [27]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2,random_state=0)

In [28]:
clf = LogisticRegression()
clf.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [29]:
y_pred = clf.predict(X_test)

In [30]:
from sklearn.metrics import confusion_matrix
confusion_matrix=confusion_matrix(y_test,y_pred)
print('\nconfusion_matrix | LogisticRegression\n')
print(confusion_matrix)



confusion_matrix | LogisticRegression

[[ 4  5  3  8  7  2  0  0  0  0]
 [ 1 12  1  4  5  0  0  0  0  0]
 [ 6  6  3 11 10  0  0  0  0  0]
 [ 4  1  2 25  6  7  0  1  0  0]
 [ 3  6  1 31 12  1  0  0  0  0]
 [ 1  2  0 14  6  5  0  0  0  0]
 [ 0  0  1  4  0  0  0  0  0  0]
 [ 0  0  0 10  4  7  0  0  0  0]
 [ 0  0  0  1  0  1  0  1  0  0]
 [ 0  0  0  0  1  0  0  0  0  1]]


In [31]:
from sklearn import svm #Import svm model
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.metrics import classification_report

print('\nclassification_report | LogisticRegression\n')
print(classification_report(y_test, y_pred))
print("Accuracy | LogisticRegression:",metrics.accuracy_score(y_test, y_pred),"\n")



classification_report | LogisticRegression

             precision    recall  f1-score   support

          A       0.21      0.14      0.17        29
         A+       0.38      0.52      0.44        23
         A-       0.27      0.08      0.13        36
          B       0.23      0.54      0.32        46
         B+       0.24      0.22      0.23        54
         B-       0.22      0.18      0.20        28
          C       0.00      0.00      0.00         5
         C+       0.00      0.00      0.00        21
         C-       0.00      0.00      0.00         3
          E       1.00      0.50      0.67         2

avg / total       0.23      0.25      0.22       247

Accuracy | LogisticRegression: 0.25101214574898784 



C:\Users\Hassana\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [32]:
from sklearn.naive_bayes import GaussianNB
# Naive Bayes 
classifier = GaussianNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print('\nconfusion_matrix | Naivebayes\n')
print(confusion_matrix)
print('\nclassification_report | Naive Bayes\n')
print(classification_report(y_test, y_pred))
print("Accuracy | Naive Bayes:",metrics.accuracy_score(y_test, y_pred),"\n") # Model Accuracy: how often is the classifier correct?



confusion_matrix | Naivebayes

[[ 4  5  3  8  7  2  0  0  0  0]
 [ 1 12  1  4  5  0  0  0  0  0]
 [ 6  6  3 11 10  0  0  0  0  0]
 [ 4  1  2 25  6  7  0  1  0  0]
 [ 3  6  1 31 12  1  0  0  0  0]
 [ 1  2  0 14  6  5  0  0  0  0]
 [ 0  0  1  4  0  0  0  0  0  0]
 [ 0  0  0 10  4  7  0  0  0  0]
 [ 0  0  0  1  0  1  0  1  0  0]
 [ 0  0  0  0  1  0  0  0  0  1]]

classification_report | Naive Bayes

             precision    recall  f1-score   support

          A       0.17      0.14      0.15        29
         A+       0.37      0.30      0.33        23
         A-       0.00      0.00      0.00        36
          B       0.08      0.07      0.07        46
         B+       0.17      0.09      0.12        54
         B-       0.12      0.25      0.16        28
          C       0.03      0.40      0.06         5
         C+       0.00      0.00      0.00        21
         C-       0.00      0.00      0.00         3
          E       0.00      0.00      0.00         2

avg / total   

C:\Users\Hassana\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [33]:
clf = svm.SVC(kernel='linear') #Create a svm Classifier
clf.fit(X_train, y_train) #Train the model using the training sets

y_pred = clf.predict(X_test)
print('\nconfusion_matrix | SVM\n')
print(confusion_matrix)

print('\nclassification_report | svm\n')
print(classification_report(y_test, y_pred))
print("Accuracy | SVM:",metrics.accuracy_score(y_test, y_pred),"\n") # Model Accuracy



confusion_matrix | SVM

[[ 4  5  3  8  7  2  0  0  0  0]
 [ 1 12  1  4  5  0  0  0  0  0]
 [ 6  6  3 11 10  0  0  0  0  0]
 [ 4  1  2 25  6  7  0  1  0  0]
 [ 3  6  1 31 12  1  0  0  0  0]
 [ 1  2  0 14  6  5  0  0  0  0]
 [ 0  0  1  4  0  0  0  0  0  0]
 [ 0  0  0 10  4  7  0  0  0  0]
 [ 0  0  0  1  0  1  0  1  0  0]
 [ 0  0  0  0  1  0  0  0  0  1]]

classification_report | svm

             precision    recall  f1-score   support

          A       0.17      0.14      0.15        29
         A+       0.38      0.39      0.38        23
         A-       0.40      0.17      0.24        36
          B       0.23      0.70      0.35        46
         B+       0.19      0.17      0.18        54
         B-       0.00      0.00      0.00        28
          C       0.00      0.00      0.00         5
         C+       0.00      0.00      0.00        21
         C-       0.00      0.00      0.00         3
          E       0.00      0.00      0.00         2

avg / total       0.20      0

C:\Users\Hassana\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [34]:
from sklearn.neural_network import MLPClassifier
mlp=MLPClassifier()
mlp.fit(X_train,y_train)
y_pred=mlp.predict(X_test)
print('\nconfusion_matrix | Multilayer Perceptron\n')
print(confusion_matrix)

print('\nclassification_report | mlp\n')
print(classification_report(y_test, y_pred))
print("Accuracy | MLP:",metrics.accuracy_score(y_test, y_pred),"\n")


confusion_matrix | Multilayer Perceptron

[[ 4  5  3  8  7  2  0  0  0  0]
 [ 1 12  1  4  5  0  0  0  0  0]
 [ 6  6  3 11 10  0  0  0  0  0]
 [ 4  1  2 25  6  7  0  1  0  0]
 [ 3  6  1 31 12  1  0  0  0  0]
 [ 1  2  0 14  6  5  0  0  0  0]
 [ 0  0  1  4  0  0  0  0  0  0]
 [ 0  0  0 10  4  7  0  0  0  0]
 [ 0  0  0  1  0  1  0  1  0  0]
 [ 0  0  0  0  1  0  0  0  0  1]]

classification_report | mlp

             precision    recall  f1-score   support

          A       0.00      0.00      0.00        29
         A+       0.41      0.48      0.44        23
         A-       0.19      0.25      0.22        36
          B       0.23      0.50      0.32        46
         B+       0.23      0.13      0.17        54
         B-       0.15      0.18      0.16        28
          C       0.50      0.20      0.29         5
         C+       0.00      0.00      0.00        21
         C-       0.00      0.00      0.00         3
          E       0.00      0.00      0.00         2

avg / total

C:\Users\Hassana\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
