In [3]:
import numpy as np
import pandas as pd

In [4]:
from sklearn.linear_model import LogisticRegression

In [5]:
#csv file from train
df = pd.read_csv('e14_e15_merged.csv', sep = ',')


In [6]:
#csv file from test
df_test = pd.read_csv('e16.csv', sep = ',')

In [7]:
df.gender.replace(['Male', 'Female'], [1, 0], inplace=True)
df_test.gender.replace(['Male', 'Female'], [1, 0], inplace=True)

In [8]:
X = df.drop("final_grades",1)   #Feature Matrix
y = df["final_grades"]          #Target Variable


In [9]:
X_T = df.drop("final_grades",1)   #Feature Matrix
y_T = df["final_grades"]          #Target Variable

In [10]:
clf = LogisticRegression()
clf.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [11]:
y_pred = clf.predict(X_T)

In [12]:
from sklearn.metrics import confusion_matrix
confusion_matrix=confusion_matrix(y_T,y_pred)

In [13]:
print('\nconfusion_matrix | LogisticRegression\n')
print(confusion_matrix)



confusion_matrix | LogisticRegression

[[19 33 16  9 51  1  0  0  0]
 [13 67 16  7 32  1  0  0  0]
 [12 34 30  8 64  3  1  0  0]
 [ 6 21 13 32 52  6  1  0  0]
 [11 26 18 20 89  1  2  0  0]
 [ 4  6  3 16 38  7  0  0  0]
 [ 0  0  0  3  3  3  0  0  0]
 [ 2  0  0  6  9  2  1  0  0]
 [ 0  0  0  0  1  0  0  0  1]]


In [14]:
from sklearn import svm #Import svm model
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.metrics import classification_report

print('\nclassification_report | LogisticRegression\n')
print(classification_report(y_T, y_pred))
print("Accuracy | LogisticRegression:",metrics.accuracy_score(y_T, y_pred),"\n")



classification_report | LogisticRegression

             precision    recall  f1-score   support

          A       0.28      0.15      0.19       129
         A+       0.36      0.49      0.41       136
         A-       0.31      0.20      0.24       152
          B       0.32      0.24      0.28       131
         B+       0.26      0.53      0.35       167
         B-       0.29      0.09      0.14        74
          C       0.00      0.00      0.00         9
         C+       0.00      0.00      0.00        20
          E       1.00      0.50      0.67         2

avg / total       0.29      0.30      0.27       820

Accuracy | LogisticRegression: 0.29878048780487804 



C:\Users\Hassana\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [20]:
from sklearn.naive_bayes import GaussianNB
# Naive Bayes 
classifier = GaussianNB()
classifier.fit(X, y)
y_pred = classifier.predict(X_T)
print('\nconfusion_matrix | Naivebayes\n')
print(confusion_matrix)
print('\nclassification_report | Naive Bayes\n')
print(classification_report(y_T, y_pred))
print("Accuracy | Naive Bayes:",metrics.accuracy_score(y_T, y_pred),"\n") # Model Accuracy: how often is the classifier correct?



confusion_matrix | Naivebayes

[[19 33 16  9 51  1  0  0  0]
 [13 67 16  7 32  1  0  0  0]
 [12 34 30  8 64  3  1  0  0]
 [ 6 21 13 32 52  6  1  0  0]
 [11 26 18 20 89  1  2  0  0]
 [ 4  6  3 16 38  7  0  0  0]
 [ 0  0  0  3  3  3  0  0  0]
 [ 2  0  0  6  9  2  1  0  0]
 [ 0  0  0  0  1  0  0  0  1]]

classification_report | Naive Bayes

             precision    recall  f1-score   support

          A       0.28      0.10      0.15       129
         A+       0.38      0.28      0.32       136
         A-       0.27      0.14      0.19       152
          B       0.23      0.08      0.12       131
         B+       0.24      0.30      0.27       167
         B-       0.13      0.16      0.14        74
          C       0.08      1.00      0.14         9
         C+       0.06      0.40      0.11        20
          E       0.50      1.00      0.67         2

avg / total       0.26      0.20      0.20       820

Accuracy | Naive Bayes: 0.20121951219512196 



In [21]:
clf = svm.SVC(kernel='linear') #Create a svm Classifier
clf.fit(X, y) #Train the model using the training sets

y_pred = clf.predict(X_T)
print('\nconfusion_matrix | SVM\n')
print(confusion_matrix)

print('\nclassification_report | svm\n')
print(classification_report(y_T, y_pred))
print("Accuracy | SVM:",metrics.accuracy_score(y_T, y_pred),"\n") # Model Accuracy



confusion_matrix | SVM

[[19 33 16  9 51  1  0  0  0]
 [13 67 16  7 32  1  0  0  0]
 [12 34 30  8 64  3  1  0  0]
 [ 6 21 13 32 52  6  1  0  0]
 [11 26 18 20 89  1  2  0  0]
 [ 4  6  3 16 38  7  0  0  0]
 [ 0  0  0  3  3  3  0  0  0]
 [ 2  0  0  6  9  2  1  0  0]
 [ 0  0  0  0  1  0  0  0  1]]

classification_report | svm

             precision    recall  f1-score   support

          A       0.29      0.11      0.16       129
         A+       0.41      0.44      0.43       136
         A-       0.26      0.19      0.22       152
          B       0.38      0.09      0.15       131
         B+       0.24      0.69      0.36       167
         B-       0.00      0.00      0.00        74
          C       0.17      0.11      0.13         9
         C+       0.00      0.00      0.00        20
          E       1.00      0.50      0.67         2

avg / total       0.28      0.28      0.24       820

Accuracy | SVM: 0.28292682926829266 



C:\Users\Hassana\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [23]:
from sklearn.neural_network import MLPClassifier
mlp=MLPClassifier()
mlp.fit(X,y)
y_pred=mlp.predict(X_T)
print('\nconfusion_matrix | Multilayer Perceptron\n')
print(confusion_matrix)

print('\nclassification_report | mlp\n')
print(classification_report(y_T, y_pred))
print("Accuracy | MLP:",metrics.accuracy_score(y_T, y_pred),"\n")


confusion_matrix | Multilayer Perceptron

[[19 33 16  9 51  1  0  0  0]
 [13 67 16  7 32  1  0  0  0]
 [12 34 30  8 64  3  1  0  0]
 [ 6 21 13 32 52  6  1  0  0]
 [11 26 18 20 89  1  2  0  0]
 [ 4  6  3 16 38  7  0  0  0]
 [ 0  0  0  3  3  3  0  0  0]
 [ 2  0  0  6  9  2  1  0  0]
 [ 0  0  0  0  1  0  0  0  1]]

classification_report | mlp

             precision    recall  f1-score   support

          A       0.20      0.40      0.27       129
         A+       0.43      0.32      0.36       136
         A-       0.29      0.04      0.07       152
          B       0.25      0.21      0.23       131
         B+       0.25      0.49      0.33       167
         B-       0.00      0.00      0.00        74
          C       0.00      0.00      0.00         9
         C+       0.00      0.00      0.00        20
          E       1.00      0.50      0.67         2

avg / total       0.25      0.26      0.22       820

Accuracy | MLP: 0.2573170731707317 



C:\Users\Hassana\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [18]:
from sklearn.ensemble import RandomForestRegressor

In [25]:
from sklearn.ensemble import RandomForestRegressor
[final_grades] = pd.to_numeric([final_grades])
regressor = RandomForestRegressor()
regressor.fit(X,y)
y_pred=regressor.predict(X_T)

NameError: name 'final_grades' is not defined