In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.linear_model import LogisticRegression

In [3]:
#csv file from train
df = pd.read_csv('e14_e15_e16_merged_int.csv', sep = ',')


In [4]:
df.gender.replace(['Male', 'Female'], [1, 0], inplace=True)

In [5]:
X = df.drop("final_grades",1)   #Feature Matrix
y = df["final_grades"]          #Target Variable


In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2,random_state=0)

In [8]:
clf = LogisticRegression()
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
from sklearn.metrics import confusion_matrix
confusion_matrix=confusion_matrix(y_test,y_pred)
print('\nconfusion_matrix | LogisticRegression\n')
print(confusion_matrix)
from sklearn import svm #Import svm model
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.metrics import classification_report

print('\nclassification_report | LogisticRegression\n')
print(classification_report(y_test, y_pred))
print("Accuracy | LogisticRegression:",metrics.accuracy_score(y_test, y_pred),"\n")



confusion_matrix | LogisticRegression

[[ 48  40   0   0]
 [ 21 107   0   0]
 [  2  27   0   0]
 [  0   2   0   0]]

classification_report | LogisticRegression

             precision    recall  f1-score   support

          A       0.68      0.55      0.60        88
          B       0.61      0.84      0.70       128
          C       0.00      0.00      0.00        29
          E       0.00      0.00      0.00         2

avg / total       0.56      0.63      0.58       247

Accuracy | LogisticRegression: 0.6275303643724697 



C:\Users\Hassana\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [9]:
from sklearn.naive_bayes import GaussianNB
# Naive Bayes 
classifier = GaussianNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print('\nconfusion_matrix | Naivebayes\n')
print(confusion_matrix)
print('\nclassification_report | Naive Bayes\n')
print(classification_report(y_test, y_pred))
print("Accuracy | Naive Bayes:",metrics.accuracy_score(y_test, y_pred),"\n") # Model Accuracy: how often is the classifier correct?



confusion_matrix | Naivebayes

[[ 48  40   0   0]
 [ 21 107   0   0]
 [  2  27   0   0]
 [  0   2   0   0]]

classification_report | Naive Bayes

             precision    recall  f1-score   support

          A       0.69      0.35      0.47        88
          B       0.56      0.84      0.68       128
          C       0.20      0.07      0.10        29
          E       0.00      0.00      0.00         2

avg / total       0.56      0.57      0.53       247

Accuracy | Naive Bayes: 0.5708502024291497 



C:\Users\Hassana\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [10]:
clf = svm.SVC(kernel='linear') #Create a svm Classifier
clf.fit(X_train, y_train) #Train the model using the training sets

y_pred = clf.predict(X_test)
print('\nconfusion_matrix | SVM\n')
print(confusion_matrix)

print('\nclassification_report | svm\n')
print(classification_report(y_test, y_pred))
print("Accuracy | SVM:",metrics.accuracy_score(y_test, y_pred),"\n") # Model Accuracy



confusion_matrix | SVM

[[ 48  40   0   0]
 [ 21 107   0   0]
 [  2  27   0   0]
 [  0   2   0   0]]

classification_report | svm

             precision    recall  f1-score   support

          A       0.70      0.52      0.60        88
          B       0.60      0.85      0.71       128
          C       0.00      0.00      0.00        29
          E       0.00      0.00      0.00         2

avg / total       0.56      0.63      0.58       247

Accuracy | SVM: 0.6275303643724697 



C:\Users\Hassana\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [11]:
from sklearn.neural_network import MLPClassifier
mlp=MLPClassifier()
mlp.fit(X_train,y_train)
y_pred=mlp.predict(X_test)
print('\nconfusion_matrix | Multilayer Perceptron\n')
print(confusion_matrix)

print('\nclassification_report | mlp\n')
print(classification_report(y_test, y_pred))
print("Accuracy | MLP:",metrics.accuracy_score(y_test, y_pred),"\n")


confusion_matrix | Multilayer Perceptron

[[ 48  40   0   0]
 [ 21 107   0   0]
 [  2  27   0   0]
 [  0   2   0   0]]

classification_report | mlp

             precision    recall  f1-score   support

          A       0.55      0.61      0.58        88
          B       0.58      0.65      0.61       128
          C       0.00      0.00      0.00        29
          E       0.00      0.00      0.00         2

avg / total       0.49      0.55      0.52       247

Accuracy | MLP: 0.5546558704453441 



C:\Users\Hassana\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [14]:
from sklearn.ensemble import RandomForestRegressor
 

In [15]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor()
regressor.fit(X_train,y_train)
y_pred=regressor.predict(X_test)

ValueError: could not convert string to float: 'A'